tour/config/routes.rb
Rails.application.routes.draw do
  resources :countries do
    resources :cities do
      resources :airports
    end
  end

  root 'countries#index'
end

tour/app/models/airport.rb
class Airport < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :city
end

tour/app/models/city.rb
class City < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :country
  has_many :airports, dependent: :destroy
end

tour/app/models/country.rb
class Country < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :cities, dependent: :destroy
end

tour/app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  def new
    @airport = Airport.new(city: @city)
  end

  def create
    @city = City.find(params[:city_id])
    @airport = @city.airports.build(airport_params)
    if @airport.save
      redirect_to city_airport_path(@airport.city.id)
    else
      render 'new'
    end
  end

  def show
    @city = City.find(params[:city_id])
    @airport = @city.airports.find(params[:id])
  end

  def edit
    @airport = Airport.find(params[:id])
  end

  def update
    @airport = Airport.find(params[:id])
    if @airport.update_attributes(airport_params)
      redirect_to country_city_path(@airport.city.id)
    else
      render 'edit'
    end
  end

  def destroy
    @airport = Airport.find(params[:id])
    @airport.destroy
    redirect_to country_city_path(@airport.city.id)
  end

  private
  def airport_params
    params.require(:airport).permit(:city_id, :title, :image)
  end
end

tour/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tour/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
=begin
  def index
    @country = Country.find(params[:country_id])
    @city = @country.cities.all
  end
=end

  def new
    @city = City.new
  end

  def create
    @country = Country.find(params[:country_id])
    @city = @country.cities.build(city_params)
    if @city.save
      redirect_to country_path(@city.country.id)
    else
      render 'new'
    end
  end

  def show
    @country = Country.find(params[:country_id])
    @city = @country.cities.find(params[:id])
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    if @city.update_attributes(city_params)
      redirect_to country_path(@city.country.id)
    else
      render 'edit'
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to country_path(@city.country.id)
  end

  private
  def city_params
    params.require(:city).permit(:country_id, :title, :image)
  end

end

tour/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
  end

  def show
    @country = Country.find(params[:id])
  end

  def new
    @country = Country.new
  end

  def edit
    @country = Country.find(params[:id])
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to countries_path
    else
      render 'new'
    end
  end

  def update

    @country = Country.find(params[:id])

    if @country.update_attributes(country_params)
      redirect_to country_path(@country)
    else
      render 'edit'
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    redirect_to countries_path
  end

  private

  def country_params
    params.require(:country).permit(:title, :image)
  end
end

tour/app/helpers/airports_helper.rb
module AirportsHelper
end

tour/app/helpers/cities_helper.rb
module CitiesHelper
end

tour/app/helpers/countries_helper.rb
module CountriesHelper
end

tour/app/views/cities/_form.html.erb
<%= form_with(model: [ @country, @country.cities.build ], local: true) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.hidden_field :country_id, :value => params["id"] %>

  <%= f.submit %>
<% end %>

tour/app/views/cities/edit.html.erb
<h1>Edit city</h1>

<%= form_for [ :country, @city ] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit %>
<% end %>

<%= link_to 'Back', country_path(@city.country.id) %>

tour/app/views/cities/new.html.erb
<h1>Add city</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', country_path(@city.country.id) %>

tour/app/views/cities/show.html.erb
<h1><%= @city.title %></h1>

<%= image_tag(@city.image.url, alt: 'Image') if @city.image? %>

<div>
  <%= link_to 'Edit', edit_country_city_path(@city.country, @city) %>
  <%= link_to 'Delete', country_city_path(@city.country, @city),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</div>

<h2>Add new airport</h2>
<%= render :partial => 'airports/form', :locals => {:city => @city.airports.build} %>

<h2>Airports:</h2>

<% @city.airports.each do |airport| %>
  <p><%= airport.title %></p>
  <div>
    <%= link_to 'Show', [@city, airport] %>
    <%= link_to 'Delete', [@city, airport],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

<p><%= link_to 'Back', country_path(@city.country.id) %></p>

tour/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tour</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>