shop/config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :categories
  resources :products
  resources :suppliers
  resources :vendors

  root 'stores#index'

end

shop/app/models/category.rb
class Category < ApplicationRecord
  belongs_to :store
  has_many :products, dependent: :destroy

  mount_uploader :image, ImageUploader
end

shop/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :suppliers, dependent: :destroy

  mount_uploader :image, ImageUploader
end

shop/app/models/store.rb
class Store < ApplicationRecord
  has_many :categories, dependent: :destroy

  mount_uploader :image, ImageUploader
end

shop/app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :product
  has_many :vendors, dependent: :destroy

  mount_uploader :image, ImageUploader
end

shop/app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :supplier

  mount_uploader :image, ImageUploader
end

shop/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new(store: @store)
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to store_path(@category.store.id)
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to store_path(@category.store.id)
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to store_path(@category.store.id)
  end

  private
  def category_params
    params.require(:category).permit(:store_id,:title, :image)
  end

end

shop/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new(category: @category)
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      redirect_to category_path(@product.category.id)
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to category_path(@product.category.id)
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to category_path(@product.category.id)
  end

  private
  def product_params
    params.require(:product).permit(:category_id,:title, :image)
  end
end

shop/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def edit
    @store = Store.find(params[:id])
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to stores_path
    else
      render 'new'
    end
  end

  def update
    @store = Store.find(params[:id])
    if @store.update_attributes(store_params)
      redirect_to store_path(@store)
    else
      render 'edit'
    end
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    redirect_to stores_path
  end

  private

  def store_params
    params.require(:store).permit(:title, :image)
  end
end

shop/app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def new
    @supplier = Supplier.new(product: @product)
  end

  def create
    @supplier = Supplier.create(supplier_params)
    if @supplier.save
      redirect_to product_path(@supplier.product.id)
    else
      render 'new'
    end
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    @supplier = Supplier.find(params[:id])
    if @supplier.update_attributes(supplier_params)
      redirect_to product_path(@supplier.product.id)
    else
      render 'edit'
    end
  end

  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.destroy
    redirect_to product_path(@supplier.product.id)
  end

  private
  def supplier_params
    params.require(:supplier).permit(:product_id,:title, :image)
  end
end

shop/app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def new
    @vendor = Vendor.new(supplier: @supplier)
  end

  def create
    @vendor = Vendor.create(vendor_params)
    if @vendor.save
      redirect_to supplier_path(@vendor.supplier.id)
    else
      render 'new'
    end
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])
    if @vendor.update_attributes(vendor_params)
      redirect_to supplier_path(@vendor.supplier.id)
    else
      render 'edit'
    end
  end

  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy
    redirect_to supplier_path(@vendor.supplier.id)
  end

  private
  def vendor_params
    params.require(:vendor).permit(:supplier_id,:title, :image)
  end
end

shop/app/helpers/categories_helper.rb
module CategoriesHelper
end

shop/app/helpers/category_helper.rb
module CategoryHelper
end

shop/app/helpers/products_helper.rb
module ProductsHelper
end

shop/app/helpers/store_helper.rb
module StoreHelper
end

shop/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

shop/app/helpers/vendors_helper.rb
module VendorsHelper
end

shop/app/views/suppliers/_form.html.erb
<%= form_for supplier do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.hidden_field :product_id, :value => params["id"] %>

  <%= f.submit %>
<% end %>

shop/app/views/suppliers/edit.html.erb
<h1>Edit supplier</h1>

<%= form_for @supplier do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit %>
<% end %>

<%= link_to 'Back', product_path(@supplier.product.id) %>

shop/app/views/suppliers/new.html.erb
<h1>Add supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Back', product_path(@supplier.product.id) %>

shop/app/views/suppliers/show.html.erb
<h1><%= @supplier.title %></h1>

<%= image_tag(@supplier.image.url, alt: 'Image') if @supplier.image? %>
<div>
  <%= link_to 'Edit', edit_supplier_path(@supplier) %>
  <%= link_to 'Delete', @supplier,
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</div>

<h2>Add new vendor</h2>
<%= render :partial => 'vendors/form', :locals => {:vendor => Vendor.new} %>

<h2>Vendors:</h2>

<% @supplier.vendors.each do |vendor| %>
  <p><%= vendor.title %></p>
  <div>
    <%= link_to 'Show', vendor %>
    <%= link_to 'Edit', edit_vendor_path(vendor) %>
    <%= link_to 'Delete', vendor,
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

<%= link_to 'Back', product_path(@supplier.product.id) %>